---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: |
          ./gradlew jar
           git_hash=$(git rev-parse --short "$GITHUB_SHA")
           echo "git_hash=$git_hash" >> $GITHUB_ENV
           echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
           echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest"
          files: /home/runner/work/duck-progress-bar/duck-progress-bar/builds/duck-progress-bar-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}